version: 1

jobs:
  test:
    image: thrive/launcher:v6
    cache:
      loadFrom:
        - v3-{Branch}-build
      writeTo: v3-{Branch}-build
      system:
        /root/.nuget: v3-nuget
    steps:
      - run:
           command: dotnet restore
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Test
          command: dotnet test
  lint:
    image: thrive/launcher:v6
    cache:
      loadFrom:
        - v3-{Branch}-build
      writeTo: v3-{Branch}-build
      system:
        /root/.nuget: v3-nuget
    steps:
      - run:
          name: Build list of changed files
          # Remove the cat here once artifact uploads is done:
          command: |
            git diff-tree --no-commit-id --name-only -r HEAD..origin/$CI_DEFAULT_BRANCH > files_to_check.txt
            git diff-tree --no-commit-id --name-only -r HEAD..$CI_EARLIER_COMMIT >> files_to_check.txt || echo compare with previous commit failed
            echo Changed files:
            cat files_to_check.txt
      - run:
          command: dotnet restore
      - run:
          name: Build with warnings
          command: dotnet run --project Scripts -- check compile
      - run:
          name: File based checks
          command: dotnet run --project Scripts -- check files
      - run:
          name: Jetbrains inspectcode
          command: dotnet run --project Scripts -- check inspectcode
      - run:
          name: Code reformatting
          command: dotnet run --project Scripts -- check cleanupcode rewrite
      - run:
          when: always
          name: Check cleanup changes
          command: |
            git diff > cleanup_diff.patch
            if grep -q '[^[:space:]]' < cleanup_diff.patch; then
                echo "Code cleanup found things to be fixed:"
                cat cleanup_diff.patch
                exit 1
            else
                echo "No changes made"
                rm -f cleanup_diff.patch
            fi
